### ISSUE TITLE
weird legend when using color values from a column

### ISSUE THREAD

**Issue by hewag1975** [r-spatial/mapview#240]
Hi Tim,
not sure if this is an issue or the bug is in front of the computer ;-)
I want to map factor levels to colors in mapview. As I am frequently mapping only spatial subsets of my dataset where some factor levels are not present I wanted to make sure to display the correct colors by simply adding a col to the dataset with the color value in it. Whereas mapping on the map works fine, the legend is incorrect. Here is a reprex with the breweries dataset:

```
library(mapview)
library(tidyverse)

# adding some random factor
breweries = breweries %>% 
  mutate(FACT = factor(sample(x = c("A", "B", "C", "D"), 
                              size = nrow(breweries), replace = TRUE)))

cols = c("red", "green", "blue", "orange")

breweries %>% 
  mapview(zcol = "FACT", col.regions = cols)
```
As I have created four factor levels and defined four colors, everything is fine:

![image](https://user-images.githubusercontent.com/38189568/67275134-3d40cb00-f4c2-11e9-8494-e1bc716bdfec.png)

Now, if I omit records with factor level "D", the legend is correct ("C" gets blue), whereas records with level "C" on the map are displayed in orange.
```
breweries %>% 
  filter(FACT != "D") %>% 
  mapview(zcol = "FACT", col.regions = cols)
```
![image](https://user-images.githubusercontent.com/38189568/67275356-b6402280-f4c2-11e9-9e71-7f2fea92c6f5.png)

Appending the colors as a new column to the dataset resolves the problem of the wrong assignment on the map, but produces a weird legend:

```
breweries = breweries %>% 
  mutate(COL = cols[match(breweries$FACT, c("A", "B", "C", "D"))])

breweries %>% 
  filter(FACT != "D") %>% 
  mapview(zcol = "FACT", col.regions = .$COL)
```
![image](https://user-images.githubusercontent.com/38189568/67275956-f8b62f00-f4c3-11e9-90a8-fa7cdce081b7.png)

Here´s the session:
```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.4.0     stringr_1.4.0     dplyr_0.8.3       purrr_0.3.2       readr_1.3.1       tidyr_0.8.99.9000 tibble_2.1.3     
 [8] ggplot2_3.2.1     tidyverse_1.2.1   mapview_2.7.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         lubridate_1.7.4    lattice_0.20-38    png_0.1-7          class_7.3-15       assertthat_0.2.1  
 [7] zeallot_0.1.0      digest_0.6.20      mime_0.7           cellranger_1.1.0   R6_2.4.0           backports_1.1.4   
[13] leafpop_0.0.1      stats4_3.6.1       e1071_1.7-2        httr_1.4.1         pillar_1.4.2       rlang_0.4.0       
[19] lazyeval_0.2.2     readxl_1.3.1       rstudioapi_0.10    raster_3.0-2       webshot_0.5.1      htmlwidgets_1.3   
[25] munsell_0.5.0      shiny_1.3.2        broom_0.5.2        compiler_3.6.1     httpuv_1.5.1       modelr_0.1.5      
[31] pkgconfig_2.0.2    base64enc_0.1-3    htmltools_0.3.6    tidyselect_0.2.5   codetools_0.2-16   viridisLite_0.3.0 
[37] withr_2.1.2        crayon_1.3.4       later_0.8.0        sf_0.7-7           grid_3.6.1         nlme_3.1-140      
[43] jsonlite_1.6       satellite_1.0.1    xtable_1.8-4       gtable_0.3.0       lifecycle_0.1.0    DBI_1.0.0         
[49] magrittr_1.5       units_0.6-4        scales_1.0.0       KernSmooth_2.23-15 cli_1.1.0          stringi_1.4.3     
[55] promises_1.0.1     leaflet_2.0.2      sp_1.3-1           xml2_1.2.2         vctrs_0.2.0        generics_0.0.2    
[61] tools_3.6.1        leafem_0.0.1       glue_1.3.1         hms_0.5.1          crosstalk_1.0.0    yaml_2.2.0        
[67] colorspace_1.4-1   rvest_0.3.4        classInt_0.4-1     haven_2.1.1       
```
Again, if there is overall a better way how to do this, feel free to remind me ;-)
Cheers, Hendrik

**Comment by tim-salabim** [comment]
ok, so far I've been able to tackle your first example... the second still needs work

**Comment by tim-salabim** [comment]
@hewag1975 with the above commit, the issue should be solved. Can you please try and report back if this works as expected now?

**Comment by hewag1975** [comment]
@tim-salabim factor partially solved from my poc. Legend and map are correct if I omit a certain factor level, but adding the color to the dataset as a variable still produces a wrong mapping between legend and points (though the legend now looks fine visually).

**Comment by tim-salabim** [comment]
Do you have an example? Also, did you use the latest develop version? I added another commit because some things weren't solved with the one mentioned above.

**Comment by hewag1975** [comment]
Actually I forked the repo, cloned it locally and tested from there. I was simply re-running the reprex above. If you are looking at the last part of it (adding color as a col) you should see it.

**Comment by tim-salabim** [comment]
Ok, so the above commit should hopefully finally solve the issue. At least for me all examples above behave nicely now... Please re-check and PLEASE close the issue if it now works for you :-)

**Comment by hewag1975** [comment]
Ok, retested and everything looks fine now. Thanks lot!
