### ISSUE TITLE
Mapview: Inconsistent popup content when burst=T

### ISSUE THREAD

**Issue by PascalIrz** [r-spatial/mapview#396]
Hi @tim-salabim, thanks for sharing the mapview package !  

My problem occurs when using the `burst=T` argument in mapview() with points sf data. Then the popup tables that are displayed do not match the points.    
I tried updating R (=>4.1.1) and RStudio (=>1.4.1717) but it did not change anything.  
I work on Windows 10.  
A reproducible exemple below.   

`library(tidyverse)      
 library(mapview)`    

`data <- data.frame(  
  species = c("APP", "ASA", "ASL", "APP", "ASA", "ASL"),  
  locality = c("Liffre", "Lizio", "Brehand", "StCongard", "Fegreac", "Plemet"),  
  x = c(-1.52, -2.50, -2.63, -2.33, -2.05, -2.54),  
  y = c(48.23, 47.87, 48.37, 47.77, 47.57, 48.17)  
)`

In this dataset, each point reports the occurrence of a species and the name of the locality. All localities have different names and each species occurs twice. The southernmost point is locality "Fegreac" with rowname "5".

The output works fine with `burst=F`, with the popup displayed for each point indicating a different locality name:

`data %>% 
  sf::st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  mapview(zcol = "species",
          col.regions = c("red", "blue", "black"),
          burst = F,
          homebutton = F)`

![image](https://user-images.githubusercontent.com/20923555/134205263-4ef6563b-46c0-4b17-be76-dbdabd196738.png)

The problem occurs with `burst = T`:

`data %>% 
  sf::st_as_sf(coords = c("x", "y"), crs = 4326) %>% 
  mapview(zcol = "species",
          col.regions = c("red", "blue", "black"),
          burst = T,
          homebutton = F)`

![image](https://user-images.githubusercontent.com/20923555/134205781-5e7d5866-1c8b-44d2-80cc-a832b78ab5b4.png)

We can see here that the popup displayed on the southernmost point indicates locality "StCongard", which is wrong. I notices that the popups displayed for each of the 2 occurrences of any given species are identical, including for locality name, which does not match the data.

Would be great if you had any suggestion, Tim, though I understand you are very busy!

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.10.2 magrittr_2.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7              svglite_2.0.0           lubridate_1.7.10        lattice_0.20-44         leaflet.providers_1.9.0
 [6] png_0.1-7               class_7.3-19            assertthat_0.2.1        digest_0.6.27           utf8_1.2.2             
[11] V8_3.4.2                R6_2.5.1                leafpop_0.1.0           stats4_4.1.1            evaluate_0.14          
[16] e1071_1.7-8             httr_1.4.2              pillar_1.6.2            rlang_0.4.11            uuid_0.1-4             
[21] curl_4.3.2              geojsonlint_0.4.0       raster_3.4-13           rmarkdown_2.11          webshot_0.5.2          
[26] tod_0.1.0.9001          rgdal_1.5-27            readr_2.0.1             stringr_1.4.0           htmlwidgets_1.5.4      
[31] munsell_0.5.0           proxy_0.4-26            compiler_4.1.1          rmapshaper_0.4.5        xfun_0.26              
[36] systemfonts_1.0.2       pkgconfig_2.0.3         base64enc_0.1-3         htmltools_0.5.2         tidyselect_1.1.1       
[41] tibble_3.1.4            httpcode_0.3.0          codetools_0.2-18        jsonvalidate_1.1.0      fansi_0.5.0            
[46] crayon_1.4.1            dplyr_1.0.7             tzdb_0.1.2              sf_1.0-2                crul_1.1.0             
[51] grid_4.1.1              jsonlite_1.7.2          satellite_1.0.2         lifecycle_1.0.0         DBI_1.1.1              
[56] units_0.7-2             scales_1.1.1            KernSmooth_2.23-20      stringi_1.7.4           farver_2.1.0           
[61] leaflet_2.0.4.1         sp_1.4-5                brew_1.0-6              ellipsis_0.3.2          generics_0.1.0         
[66] vctrs_0.3.8             RColorBrewer_1.1-2      tools_4.1.1             leafem_0.1.6            glue_1.4.2             
[71] purrr_0.3.4             hms_1.1.0               crosstalk_1.1.1         fastmap_1.1.0           yaml_2.2.1             
[76] colorspace_2.0-2        classInt_0.4-3          knitr_1.34

**Comment by tim-salabim** [comment]
I'll try to look into this soon. Sorry, but I don't have a lot of time for dev at this stage

**Comment by PascalIrz** [comment]
I understand, thanks anyway for all the work you achieved on this package that I find wery handy and intiutive to use.

**Comment by bwalsh5** [comment]
I am also running into this issue when burst=T. When I turn off burst, the popups ignore the zcol choices and populate the popup with the entire dataset.

**Comment by tim-salabim** [comment]
Should work now, can you please re-try?

**Comment by bwalsh5** [comment]
Still not working for me - 

Using geoJSON data downloaded from here:

https://opendata.dc.gov/datasets/homeless-shelter-locations/explore

This line is not working: 

  mapview(homeless, color = "green", legend = FALSE, popup = popupTable(homeless, zcol=c("ADDRESS", "PROVIDER", "SUBTYPE")), burst = TRUE)  

Thank you for looking into this!

**Comment by tim-salabim** [comment]
Did you reinstall from GitHub?

**Comment by bwalsh5** [comment]
Wow, I feel stupid!
I just re-installed from GitHub, and the popups are correctly showing!
 For some reason, they are showing the same values for each of the variables I select, even though they are different in the data frame.

**Comment by tim-salabim** [comment]
@bwalsh5 not sure what you mean? Do you have a reprex?

**Comment by bwalsh5** [comment]
``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(tidyverse)
# remotes::install_github("r-spatial/mapview")
library(mapview)
library(leaflet)
library(leafpop)
# data from: https://opendata.dc.gov/datasets/homeless-shelter-locations/explore

homeless <- read_sf("~/Downloads/homeless.geojson") 


mapview(homeless, color = "green", legend = FALSE, popup = popupTable(homeless, zcol=c("ADDRESS", "PROVIDER", "SUBTYPE")), burst = TRUE)  
```

![](https://i.imgur.com/L0tLNjW.png)

<sup>Created on 2021-12-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tim-salabim** [comment]
Can you provide `homeless.geojson` here? I think you can just drag and drop it here...

**Comment by bwalsh5** [comment]
{
"type": "FeatureCollection",
"name": "Homeless_Shelter_Locations",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OBJECTID": 1, "OWNER_RENTER": "Catholic Charities", "PROVIDER": "Catholic Charities", "ADDRESS": "6010 Georgia Ave., NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.96335141, "LONGITUDE": -77.02830252, "WARD": "Ward 4", "TYPE": "Low Barrier", "SUBTYPE": "Women", "STATUS": "Active", "NUMBER_OF_BEDS": 25, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "397547.11", "YCOORD": "143938.2", "NAME": "Nativity Shelter for Women", "ZIPCODE": "20011", "WEB_URL": "https://www.catholiccharitiesdc.org/nativity/", "MAR_ID": "308177", "GIS_ID": "HomelessShelterPt_1", "GLOBALID": "{453EC7E8-81EB-4C02-B866-78996813ABD2}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.028304820744509, 38.963358873102905 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 2, "OWNER_RENTER": "Coalition for the Homeless", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "4326 14th Street NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.94384718, "LONGITUDE": -77.03300118, "WARD": "Ward 4", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 12, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "397139.11", "YCOORD": "141773.19", "NAME": "The Webster House", "ZIPCODE": "20011", "WEB_URL": "http://www.dccfh.org/programs/housing/the-webster-house", "MAR_ID": "259286", "GIS_ID": "HomelessShelterPt_2", "GLOBALID": "{D271432C-8CA8-4C02-836A-77704207EEE8}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.033003473544923, 38.943854645715803 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 3, "OWNER_RENTER": "DHS", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "1131 Spring Road NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.93637222, "LONGITUDE": -77.02915837, "WARD": "Ward 4", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 40, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "397471.98", "YCOORD": "140943.29", "NAME": "La Casa TRP", "ZIPCODE": "20010", "WEB_URL": "http://www.dccfh.org/programs/housing/la-casa-transitional-rehabilitation-program-trp", "MAR_ID": "230119", "GIS_ID": "HomelessShelterPt_3", "GLOBALID": "{84D1511E-7ACC-470C-83B7-60E321527E83}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.029160664624754, 38.9363796845292 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 4, "OWNER_RENTER": "Coalition for the Homeless", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "1318 Park Road NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.93080277, "LONGITUDE": -77.03049878, "WARD": "Ward 1", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 12, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "397355.56", "YCOORD": "140325.07", "NAME": "Park Road Transitional Program", "ZIPCODE": "20010", "WEB_URL": "http://www.dccfh.org/programs/housing/park-road-transitional-program", "MAR_ID": "231077", "GIS_ID": "HomelessShelterPt_4", "GLOBALID": "{BBBBE8E2-BB32-40E8-BBF5-BCEDFA359C5F}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.030501079223214, 38.930810228066967 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 5, "OWNER_RENTER": "Casa Ruby", "PROVIDER": "Casa Ruby", "ADDRESS": "2822 Georgia Ave NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.9267581, "LONGITUDE": -77.02315718, "WARD": "Ward 1", "TYPE": "Low Barrier", "SUBTYPE": "Youth", "STATUS": "Active", "NUMBER_OF_BEDS": 17, "ON_SITE_MEDICAL_CLINIC": "No", "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-12-19T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18-24", "HOW_TO_ACCESS": "Show Up and/or Call the Shelter ", "LGBTQ_FOCUSED": "Yes", "XCOORD": "397992.01", "YCOORD": "139875.89", "NAME": "Casa Ruby", "ZIPCODE": "20001", "WEB_URL": "http://www.casaruby.org/index.html", "MAR_ID": "232586", "GIS_ID": "HomelessShelterPt_5", "GLOBALID": "{C95175C1-8315-4E9E-8338-FC57F14AF0C2}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.023159474895294, 38.926765559532782 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 6, "OWNER_RENTER": "DHS", "PROVIDER": "Catholic Charities", "ADDRESS": "2210 Adams Place, NE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.91962229, "LONGITUDE": -76.97487627, "WARD": "Ward 5", "TYPE": "Low Barrier", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 150, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "402178.73", "YCOORD": "139083.8", "NAME": "Adams Place Shelter", "ZIPCODE": "20018", "WEB_URL": "https://www.catholiccharitiesdc.org/housing-shelter/adamsplace/", "MAR_ID": "50358", "GIS_ID": "HomelessShelterPt_6", "GLOBALID": "{ACDDF2E5-F7A8-44AF-8998-92E40DABB34A}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.97487854623607, 38.919629752981251 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 7, "OWNER_RENTER": "DHS", "PROVIDER": "Catholic Charities", "ADDRESS": "1355 New York Avenue, NE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.91506826, "LONGITUDE": -76.98582943, "WARD": "Ward 5", "TYPE": "Low Barrier", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 360, "ON_SITE_MEDICAL_CLINIC": "Yes", "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "401228.95", "YCOORD": "138578.06", "NAME": "New York Avenue Shelter", "ZIPCODE": "20002", "WEB_URL": "https://www.catholiccharitiesdc.org/housing-shelter/newyorkave/", "MAR_ID": "66060", "GIS_ID": "HomelessShelterPt_7", "GLOBALID": "{EAEB443E-CB16-4E3F-B610-26614ACA7033}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.985831714163837, 38.915075720316899 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 8, "OWNER_RENTER": "Coalition for the Homeless", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "455/457 Florida Avenue NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.91467276, "LONGITUDE": -77.01772294, "WARD": "Ward 1", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 22, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "398462.96", "YCOORD": "138534.21", "NAME": "Mickey Leland House", "ZIPCODE": "20001", "WEB_URL": "http://www.dccfh.org/programs/housing/mickey-leland-house", "MAR_ID": "218238", "GIS_ID": "HomelessShelterPt_8", "GLOBALID": "{E9532D5B-1C2D-4434-B229-BCF4CCBB15BC}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.017725228921933, 38.914680218783396 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 9, "OWNER_RENTER": "DHS", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "1725 Lincoln Road NE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.91359824, "LONGITUDE": -77.00790385000001, "WARD": "Ward 5", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 100, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "399314.52", "YCOORD": "138414.81", "NAME": "Emery Work Bed Program", "ZIPCODE": "20002", "WEB_URL": "http://www.dccfh.org/programs/housing/emery-work-bed-program-ewbp", "MAR_ID": "155923", "GIS_ID": "HomelessShelterPt_9", "GLOBALID": "{11E03B50-1BBB-4738-8DEE-1DC2343EC45D}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.007906139110986, 38.913605700430047 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 10, "OWNER_RENTER": "DHS", "PROVIDER": "New Endeavors by Women", "ADDRESS": "611 N St. NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.90747184, "LONGITUDE": -77.02055934000001, "WARD": "Ward 6", "TYPE": "Transitional/Permanent", "SUBTYPE": "Women", "STATUS": "Active", "NUMBER_OF_BEDS": 15, "ON_SITE_MEDICAL_CLINIC": "No", "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "398216.79", "YCOORD": "137734.9", "NAME": "New Endeavors by Women", "ZIPCODE": "20001", "WEB_URL": "http://nebw.org/", "MAR_ID": "279854", "GIS_ID": "HomelessShelterPt_10", "GLOBALID": "{8AC9E3C9-B5AD-4AF3-8A2D-A9CC7EC4B7E9}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.020561632683368, 38.907479295820359 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 11, "OWNER_RENTER": "DHS", "PROVIDER": "Coalition for the Homeless", "ADDRESS": "635 Eye Street, NE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.90106219, "LONGITUDE": -76.99701934, "WARD": "Ward 6", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 85, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Coordinated Assessment & Housing Placement (CAHP) Process", "LGBTQ_FOCUSED": null, "XCOORD": "400258.55", "YCOORD": "137023.18", "NAME": "Blair House ", "ZIPCODE": "20002", "WEB_URL": "http://www.dccfh.org/programs/housing/blair-transitional-rehabilitation-program", "MAR_ID": "2520", "GIS_ID": "HomelessShelterPt_11", "GLOBALID": "{C302FD3B-B5F9-4456-A96F-32E5DFF9C8E5}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.99702162404688, 38.901069642301366 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 12, "OWNER_RENTER": "DHS", "PROVIDER": "N Street Village", "ADDRESS": "810 5th St. NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.90036097, "LONGITUDE": -77.01916906, "WARD": "Ward 2", "TYPE": "Low Barrier", "SUBTYPE": "Women", "STATUS": "Active", "NUMBER_OF_BEDS": 213, "ON_SITE_MEDICAL_CLINIC": "Yes", "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "398337.21", "YCOORD": "136945.51", "NAME": "Pat Handy Shelter for Women", "ZIPCODE": "20001", "WEB_URL": "http://www.nstreetvillage.org/about-the-village/programs-impact/housing-community/", "MAR_ID": "218764", "GIS_ID": "HomelessShelterPt_12", "GLOBALID": "{5EAE5DE1-5BF3-420A-998E-5C9A3FA39B49}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.019171350350149, 38.900368427575003 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 13, "OWNER_RENTER": "Central Union Mission", "PROVIDER": "Central Union Mission", "ADDRESS": "65 Massachusetts Avenue, NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.89868476, "LONGITUDE": -77.01106317, "WARD": "Ward 6", "TYPE": "Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 25, "ON_SITE_MEDICAL_CLINIC": "Yes", "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "399040.32", "YCOORD": "136759.32", "NAME": "Central Union Mission", "ZIPCODE": "20001", "WEB_URL": "http://www.missiondc.org/", "MAR_ID": "237153", "GIS_ID": "HomelessShelterPt_13", "GLOBALID": "{6CDD0B36-46A0-499A-A0F6-B414C351146F}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.011065459001671, 38.898692209955883 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 14, "OWNER_RENTER": "Sasha Bruce", "PROVIDER": "Sasha Bruce Youthworks", "ADDRESS": "1022 Maryland Ave NE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.89703331, "LONGITUDE": -76.99183285, "WARD": "Ward 6", "TYPE": "Crisis", "SUBTYPE": "Youth-Minors", "STATUS": "Active", "NUMBER_OF_BEDS": 10, "ON_SITE_MEDICAL_CLINIC": "No", "DGS_CONFIRMED": null, "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-12-19T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "11-17", "HOW_TO_ACCESS": "Show Up and/or Call the Shelter ", "LGBTQ_FOCUSED": null, "XCOORD": "400708.48", "YCOORD": "136575.97", "NAME": "Sasha Bruce Youthworks", "ZIPCODE": "20002", "WEB_URL": "http://www.sashabruce.org/programs/safehomes/sasha-bruce-house/", "MAR_ID": "75415", "GIS_ID": "HomelessShelterPt_14", "GLOBALID": "{EA6603D1-C852-49A7-9BE0-A757FA7BBE2B}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.991835126437053, 38.897040765536751 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 15, "OWNER_RENTER": "DHS", "PROVIDER": "New Hope Ministries", "ADDRESS": "425 2nd St, NW", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.89550412, "LONGITUDE": -77.01329693, "WARD": "Ward 6", "TYPE": "Low Barrier/Transitional", "SUBTYPE": "Men & Women", "STATUS": "Active", "NUMBER_OF_BEDS": 964, "ON_SITE_MEDICAL_CLINIC": "Yes", "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "398846.5", "YCOORD": "136406.27", "NAME": "Center for Creative Non-Violence (CCNV)", "ZIPCODE": "20001", "WEB_URL": "http://www.theccnv.org/about.htm", "MAR_ID": "299726", "GIS_ID": "HomelessShelterPt_15", "GLOBALID": "{3FA49627-0B47-4B20-8470-51312E44A8BB}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -77.013299219786091, 38.895511573694996 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 16, "OWNER_RENTER": "DHS", "PROVIDER": "Catholic Charities", "ADDRESS": "1900 Massachusetts Ave SE, Bldg. 27 ", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.88521981, "LONGITUDE": -76.97557417, "WARD": "Ward 7", "TYPE": "Low Barrier/Transitional", "SUBTYPE": "Women", "STATUS": "Active", "NUMBER_OF_BEDS": 100, "ON_SITE_MEDICAL_CLINIC": null, "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "402119.23", "YCOORD": "135264.83", "NAME": "Harriet Tubman Shelter & Day Center", "ZIPCODE": "20003", "WEB_URL": "https://www.catholiccharitiesdc.org/harriettubman/", "MAR_ID": "301068", "GIS_ID": "HomelessShelterPt_16", "GLOBALID": "{8053AA4B-2015-4C16-82EE-4EE1E6B979B6}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.975576443652699, 38.885227257488928 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 17, "OWNER_RENTER": "DHS", "PROVIDER": "Catholic Charities", "ADDRESS": "2700 Martin Luther King Jr. Ave, SE ", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.85068463, "LONGITUDE": -76.99472857000001, "WARD": "Ward 8", "TYPE": "Low Barrier/Transitional", "SUBTYPE": "Men", "STATUS": "Active", "NUMBER_OF_BEDS": 450, "ON_SITE_MEDICAL_CLINIC": "Yes", "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-11-15T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18+", "HOW_TO_ACCESS": "Show Up and/or Call Shelter Hotline (311)", "LGBTQ_FOCUSED": null, "XCOORD": "400457.58", "YCOORD": "131430.9", "NAME": "801 East - Shelter", "ZIPCODE": "20032", "WEB_URL": "https://www.catholiccharitiesdc.org/housing-shelter/801east/", "MAR_ID": "301562", "GIS_ID": "HomelessShelterPt_17", "GLOBALID": "{13D8452A-F859-4EDD-8C43-CBFB54285583}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.99473085268373, 38.850692076766549 ] } },
{ "type": "Feature", "properties": { "OBJECTID": 18, "OWNER_RENTER": "Covenant House", "PROVIDER": "Covenant House Washington", "ADDRESS": "2001 Mississippi Ave SE", "CITY": "Washington", "STATE": "DC", "LATITUDE": 38.84359614, "LONGITUDE": -76.97423215000001, "WARD": "Ward 8", "TYPE": "Low Barrier", "SUBTYPE": "Youth", "STATUS": "Active", "NUMBER_OF_BEDS": 20, "ON_SITE_MEDICAL_CLINIC": "No", "DGS_CONFIRMED": "Yes", "DHS_CONFIRMED": "Yes", "ALREADY_PUBLIC_INFORMATION": "Yes", "LAST_UPDATED_BY_DHS": "2017-12-19T05:00:00Z", "PUBLISH_TO_ODP": "Yes", "AGES_SERVED": "18-24", "HOW_TO_ACCESS": "Show Up and/or Call the Shelter", "LGBTQ_FOCUSED": null, "XCOORD": "402236.97", "YCOORD": "130644.33", "NAME": "Covenant House Washington", "ZIPCODE": "20020", "WEB_URL": "http://covenanthousedc.org/our-services/housing/", "MAR_ID": "295846", "GIS_ID": "HomelessShelterPt_18", "GLOBALID": "{973C9A63-B8BC-48DA-AD59-11F94309FF71}", "CREATOR": null, "CREATED": null, "EDITOR": null, "EDITED": null }, "geometry": { "type": "Point", "coordinates": [ -76.974234424702516, 38.843603582453305 ] } }
]
}

**Comment by bwalsh5** [comment]
Sorry, the geoJSON file type was rejected by the file upload system, so I copied and pasted the JSON. 
Can also be downloaded here:
[https://opendata.dc.gov/datasets/homeless-shelter-locations/explore](https://opendata.dc.gov/datasets/homeless-shelter-locations/explore)

**Comment by PascalIrz** [comment]
Hi @tim-salabim, I had a quick test and the issue seems to be fixed. Thants a lot !

**Comment by tim-salabim** [comment]
@bwalsh5 should work now. Can you please re-install and try again?

**Comment by bwalsh5** [comment]
Yes, the problem appears to be fixed! 
Thanks again!
