### ISSUE TITLE
Mapview not rendering shapes

### ISSUE THREAD

**Issue by plnnr** [r-spatial/mapview#413]
Mapview fails to render shapes, however, the legend renders and there are shapes. 

This fails:
` tigris::tracts(state = "WA", county = "Clark", cb = TRUE, year = 2019, class = "sf") %>% mapview() `

Here is the output:
![image](https://user-images.githubusercontent.com/7258833/157159318-b794612e-5770-4271-ba02-60bb1bab96d9.png)

It seems to happen inconsistently. Even when I run `rm(list=ls()) ; gc()` and restart RStudio and even restart my computer, it doesn't seem to fix the issue. But now and then, the shapes render as they are supposed to.

Curiously, knitting a RMarkdown doc will allow it to render in the HTML ouput.

Here is my session info:
```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mapview_2.10.4.9005  tigris_1.6           sf_1.0-6             forcats_0.5.1       
 [5] stringr_1.4.0        dplyr_1.0.8          purrr_0.3.4          readr_2.1.2         
 [9] tidyr_1.2.0          tibble_3.1.6         ggplot2_3.3.5        tidyverse_1.3.1.9000

loaded via a namespace (and not attached):
 [1] fs_1.5.2                satellite_1.0.4         lubridate_1.8.0         RColorBrewer_1.1-2     
 [5] webshot_0.5.2           httr_1.4.2              tools_4.1.2             backports_1.4.0        
 [9] utf8_1.2.2              rgdal_1.5-28            R6_2.5.1                KernSmooth_2.23-20     
[13] DBI_1.1.2               colorspace_2.0-3        raster_3.5-15           withr_2.5.0            
[17] sp_1.4-6                tidyselect_1.1.2        leaflet_2.1.0           curl_4.3.2             
[21] compiler_4.1.2          leafem_0.1.6            cli_3.2.0               rvest_1.0.2            
[25] xml2_1.3.3              scales_1.1.1            classInt_0.4-3          proxy_0.4-26           
[29] rappdirs_0.3.3          digest_0.6.29           foreign_0.8-81          rmarkdown_2.11         
[33] rio_0.5.29              base64enc_0.1-3         pkgconfig_2.0.3         htmltools_0.5.2        
[37] dbplyr_2.1.1            fastmap_1.1.0           htmlwidgets_1.5.4       rlang_1.0.1            
[41] readxl_1.3.1            rstudioapi_0.13         farver_2.1.0            generics_0.1.2         
[45] jsonlite_1.8.0          crosstalk_1.2.0         zip_2.2.0               googlesheets4_1.0.0    
[49] magrittr_2.0.2          Rcpp_1.0.8              munsell_0.5.0           fansi_1.0.2            
[53] lifecycle_1.0.1         terra_1.5-21            stringi_1.7.6           yaml_2.3.5             
[57] grid_4.1.2              maptools_1.1-2          crayon_1.5.0            lattice_0.20-45        
[61] haven_2.4.3             hms_1.1.1               knitr_1.36              pillar_1.7.0           
[65] uuid_1.0-3              dtplyr_1.2.0            codetools_0.2-18        stats4_4.1.2           
[69] reprex_2.0.1            glue_1.6.2              evaluate_0.15           leaflet.providers_1.9.0
[73] data.table_1.14.2       modelr_0.1.8            vctrs_0.3.8             png_0.1-7              
[77] tzdb_0.2.0              cellranger_1.1.0        gtable_0.3.0            assertthat_0.2.1       
[81] openxlsx_4.2.4          xfun_0.30               broom_0.7.10            e1071_1.7-9            
[85] class_7.3-19            googledrive_2.0.0       gargle_1.2.0            units_0.8-0            
[89] ellipsis_0.3.2         
```

**Comment by tim-salabim** [comment]
Hi this is already fixed in the development version. 

```r
remotes::install_github("r-spatial/mapview")
```

**Comment by plnnr** [comment]
@tim-salabim Thank you! Updated to the latest and it works... I should have updated before posting, although it was only off by a small bit `mapview_2.10.4.9005` vs `mapview_2.10.4.9006`.

**Comment by plnnr** [comment]
This issue persists. I've restarted my machine and re-loaded R. Here again is my session info.


```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mapview_2.10.4.9006   furrr_0.2.3           future_1.23.0        
 [4] tigris_1.6.0.9000     sf_1.0-8              tidycensus_1.1.2.9000
 [7] forcats_0.5.1         stringr_1.4.0         dplyr_1.0.8          
[10] purrr_0.3.4           readr_2.1.2           tidyr_1.2.0          
[13] tibble_3.1.6          ggplot2_3.3.5         tidyverse_1.3.1.9000 

loaded via a namespace (and not attached):
 [1] googledrive_2.0.0       leafem_0.1.6            colorspace_2.0-3       
 [4] ellipsis_0.3.2          class_7.3-19            rio_0.5.29             
 [7] leaflet_2.1.0           rgdal_1.5-29            snakecase_0.11.0       
[10] satellite_1.0.4         base64enc_0.1-3         fs_1.5.2               
[13] rstudioapi_0.13         proxy_0.4-26            listenv_0.8.0          
[16] farver_2.1.0            remotes_2.4.2           fansi_1.0.2            
[19] lubridate_1.8.0         xml2_1.3.3              codetools_0.2-18       
[22] jsonlite_1.8.0          broom_0.7.10            dbplyr_2.1.1           
[25] png_0.1-7               compiler_4.1.2          httr_1.4.2             
[28] backports_1.4.0         assertthat_0.2.1        fastmap_1.1.0          
[31] gargle_1.2.0            cli_3.2.0               s2_1.0.7               
[34] leaflet.providers_1.9.0 htmltools_0.5.2         tools_4.1.2            
[37] crsuggest_0.3.1         gtable_0.3.0            glue_1.6.2             
[40] wk_0.6.0                rappdirs_0.3.3          Rcpp_1.0.8.3           
[43] cellranger_1.1.0        raster_3.5-15           vctrs_0.3.8            
[46] crosstalk_1.2.0         globals_0.14.0          openxlsx_4.2.4         
[49] rvest_1.0.2             lifecycle_1.0.1         googlesheets4_1.0.0    
[52] terra_1.5-21            scales_1.1.1            hms_1.1.1              
[55] parallel_4.1.2          RColorBrewer_1.1-2      yaml_2.3.5             
[58] curl_4.3.2              dtplyr_1.2.0            stringi_1.7.6          
[61] maptools_1.1-3          e1071_1.7-9             zip_2.2.0              
[64] rlang_1.0.2             pkgconfig_2.0.3         lattice_0.20-45        
[67] htmlwidgets_1.5.4       tidyselect_1.1.2        parallelly_1.30.0      
[70] magrittr_2.0.2          R6_2.5.1                generics_0.1.2         
[73] DBI_1.1.2               pillar_1.7.0            haven_2.4.3            
[76] foreign_0.8-81          withr_2.5.0             units_0.8-0            
[79] sp_1.4-6                janitor_2.1.0           modelr_0.1.8           
[82] crayon_1.5.0            uuid_1.0-4              KernSmooth_2.23-20     
[85] utf8_1.2.2              tzdb_0.2.0              grid_4.1.2             
[88] readxl_1.3.1            data.table_1.14.2       reprex_2.0.1           
[91] digest_0.6.29           classInt_0.4-3          webshot_0.5.2          
[94] stats4_4.1.2            munsell_0.5.0          

```

**Comment by tim-salabim** [comment]
I think you need to re-install `leafem` to get it working.

**Comment by plnnr** [comment]
@tim-salabim When I installed via `remotes::install_github('r-spatial/leafem')` it worked. Thanks again!
